-- Supabase exposes the public schema through its Data API (PostgREST) with the
-- public anon key. The app never uses that API, so enable RLS with no policies
-- to deny it everything. Prisma connects as the table owner (postgres), which
-- bypasses RLS. New tables need the same statement in their migration.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserMerge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OtpCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserRole" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Family" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FamilyLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationEvidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vouch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RosterEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Follow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Block" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Rsvp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NewsPost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
